### ISSUE TITLE
[BE] 모니터링 시스템 오류 확인 및 수정

### ISSUE THREAD

**Issue by mrcocoball** [mrcocoball/date-planner#161]
SSH 인증 적용 이후 프로메테우스 - 그라파나 메트릭 수집 관련 오류가 발생하여
모니터링 시스템이 제대로 작동하지 않고 있다. 내용을 확인해보고 수정을 해야한다.

* [x] 오류 수정
* [x] 적용

**Comment by mrcocoball** [comment]
문제 상황 정리

* API 서버 : actuator 엔드포인트 전용 포트를 별도로 할당했으나 SSL이 적용되어 http:// 요청 불가, https:// 접근 시에도 인증서 오류
  * 포트포워딩을 하지 않아 인증서 오류가 뜨는 것인지... (기존에는 localhost로서 내부망에서 접근 가능했음)
  * 포트포워딩을 해야 하는 것이라면 결국 actuator의 엔드포인트의 외부 접근을 허용하게 됨
  * 외부 접근을 막기 위해서 auth 기능을 적용한다면 시스템이 바뀌어야 할 듯
* 프로메테우스 : SSL 적용되나 인증서 오류인지 localhost:9090 으로 접근하고자 하면 인증서 오류 발생하여 UI 접근 불가
* 그라파나 : 프로메테우스와 통신은 가능, 그러나 API 서버 + 프로메테우스 서버 측 문제로 데이터 수집 안됨

**Comment by mrcocoball** [comment]
* 일단 API 서버에서는 management.server.ssl.enabled 옵션으로 SSL 적용 여부를 결정할 수 있었다...
```yaml
management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
  endpoint:
    health:
      show-details: always
  server:
    port: 9000
    ssl:
      enabled: false
```
