### ISSUE TITLE
[BE] 백엔드 API 서버 DB 컨테이너 관련 버그 수정

### ISSUE THREAD

**Issue by mrcocoball** [mrcocoball/date-planner#35]
* 현재 DB 컨테이너가 build 도중 죽어버려서 연결이 되지 않는 버그가 있음
![Image](https://user-images.githubusercontent.com/109284797/216357196-00e21d40-256f-4a2f-a784-fd24c00089ea.png)

* 확인을 해보니 mariaDB 버전 관련 이슈가 있어서 10.2 버전으로 강제 다운그레이드하여 build하니 해결되었음
```yml
FROM mariadb:10.2
#latest 버전으로 가져왔을 때 can't initialize 오류가 발생, 강제로 10.2 버전 (현재 홈 리눅스 버전이 16.04버전이므로)

ENV TZ=Asia/Seoul
```

* 추가로, docker-compose 상에서 호스트와 컨테이너 바인드 마운트를 하지 않아 이미지가 호스트 내 폴더에 저장되지 않던 이슈가 있어서 수정하였음
```yml
  backend-app:
    container_name: backend-app
    depends_on: # DB 컨테이너 실행 후 WEB을 실행시킴
      - backend-database
    image: mrcocoball/dateplanner_backend:dev
    environment: # .env 파일에 저장했던 환경 변수
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "81:8084" # 기본 포트
    volumes:
      - /home/mrcocoball/date_planner/image:/home/mrcocoball/date_planner/image
      # 호스트 경로 : 컨테이너 내부 경로 mount(연결) (해당 내용 지정 안할 경우 컨테이너 내부의 경로에만 저장이 됨)
```
